[tools]
go = "1.26.0"
rust = "1.93.1"
uv = "0.10.3"
lua = "5.5.0"
java = "26.0.0"
maven = "3.9.12"
node = "25.6.1"
lazydocker = "0.24.4"
lazygit = "0.59.0"
fzf = "0.67.0"
duf = "0.9.1"
dive = "0.13.1"
yq = "4.52.4"
jq = "1.8.1"
direnv = "2.37.1"
sops = "3.11.0"
bat = "0.26.1"
eza = "0.23.4"
fd = "10.3.0"
delta = "0.18.2"
rg = "15.1.0"
difftastic = "0.67.0"
choose = "1.3.7"
just = "1.46.0"
zoxide = "0.9.9"
claude-code = "2.1.42"
starship = "1.24.2"
terraform = "1.14.5"
pandoc = "3.9"
gh = "2.86.0"
tmux = "3.6a"
kubectl = "1.35.1"
k9s = "0.50.18"
lnav = "0.13.2"
neovim = "0.11.6"
vim = "9.2.0010"
docker-cli = "29.2.1"
docker-compose = "5.0.2"
pipx = "1.8.0"
"pipx:harlequin[postgres,mysql,s3]" = "2.5.1"
"pipx:httpie" = "3.2.4"
"pipx:jrnl" = "4.2.1"
"pipx:visidata" = "3.3"
"pipx:mitmproxy" = "12.2.1"
"pipx:ansible" = "13.3.0"
"pipx:ansible-core" = "2.20.2"
"pipx:stringshift[full]" = "0.1.2"
"github:bootandy/dust" = "1.2.4"
"github:veeso/termscp" = "0.19.1"
"github:dalance/procs" = "0.14.10"
"cargo:https://github.com/Aloxaf/silicon" = "HEAD"
