[tools]
go = "latest"
rust = "latest"
uv = "latest"
lua = "latest"
java = "latest"
maven = "latest"
node = "latest"
lazydocker = "latest"
lazygit = "latest"
fzf = "latest"
duf = "latest"
dive = "latest"
yq = "latest"
jq = "latest"
direnv = "latest"
sops = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
delta = "latest"
rg = "latest"
difftastic = "latest"
choose = "latest"
just = "latest"
zoxide = "latest"
claude-code = "latest"
starship = "latest"
terraform = "latest"
pandoc = "latest"
gh = "latest"
tmux = "latest"
kubectl = "latest"
k9s = "latest"
lnav = "latest"
neovim = "latest"
vim = "latest"
docker-cli = "latest"
docker-compose = "latest"
pipx = "latest"
"pipx:harlequin[postgres,mysql,s3]" = "latest"
"pipx:httpie" = "latest"
"pipx:jrnl" = "latest"
"pipx:visidata" = "latest"
"pipx:mitmproxy" = "latest"
"pipx:ansible" = "latest"
"pipx:ansible-core" = "latest"
"pipx:stringshift[full]" = "latest"
"cargo:du-dust" = "latest"
"cargo:termscp" = "latest"
"cargo:procs" = "latest"
"cargo:silicon" = "latest"
